/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/afk/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the caller’s active AFK record, or null when not AFK. */
        get: operations["AfkController_getOwnStatus"];
        put?: never;
        /** Mark the caller as AFK. Applies the AFK role and nickname prefix on Discord. */
        post: operations["AfkController_setOwnAfk"];
        /** Clear the caller’s AFK status. Idempotent: returns 204 even if the caller was not AFK. */
        delete: operations["AfkController_clearOwnAfk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/afk/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the caller’s paginated AFK history. */
        get: operations["AfkController_getOwnHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/afk/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AFK records across the guild (staff only). Filter via isValid. */
        get: operations["AfkController_listGuildAfk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/afk/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return a target user’s active AFK record (staff only), or null when not AFK. */
        get: operations["AfkController_getUserStatus"];
        put?: never;
        /** Mark a target user as AFK (staff only). Applies the AFK role and nickname prefix. */
        post: operations["AfkController_setUserAfk"];
        /** Clear a target user’s AFK status (staff only). Idempotent: 204 even if the user was not AFK. */
        delete: operations["AfkController_clearUserAfk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/afk/users/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return a target user’s paginated AFK history (staff only). */
        get: operations["AfkController_getUserHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a Discord OAuth access token for application access + refresh tokens. */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token; returns a new access + refresh token pair. */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh-token family (logout this session). */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke every refresh-token family for the current user (logout everywhere). */
        post: operations["AuthController_logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated user identity with freshly resolved roles. */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate an API key passed via the X-API-Key header. */
        get: operations["AuthTokenController_validate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all guild roles, sorted by position desc, @everyone excluded. */
        get: operations["CommunityController_getRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return community totals (members, recent joiners, voice minutes, messages). */
        get: operations["CommunityController_getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/members/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the newest active members ordered by joinedAt desc. */
        get: operations["CommunityController_getRecent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/members/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Slim member list for CMS autocomplete fields. Supports name fragment or ID list. */
        get: operations["CommunityController_autocomplete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/members/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulk-hydrate rich member DTOs by Discord ID list (staff page render). */
        get: operations["CommunityController_lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Searchable, sortable, paginated member directory. */
        get: operations["CommunityController_getDirectory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/members/{discordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the rich profile for a single active member. */
        get: operations["CommunityController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/digests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List content digests with optional topic and frequency filters */
        get: operations["ContentDigestController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/digests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single content digest by UUID */
        get: operations["ContentDigestController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/digests/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger digest generation for one or all topics and frequencies */
        post: operations["ContentDigestController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List content articles with optional source and topic filters */
        get: operations["ContentController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single content article by UUID or source ID */
        get: operations["ContentController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger an incremental content sync for one or all sources */
        post: operations["ContentController_triggerSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discord/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List guild channels */
        get: operations["DiscordChannelController_getChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discord/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get channel details */
        get: operations["DiscordChannelController_getChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discord/channels/{channelId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get channel message history */
        get: operations["DiscordChannelController_getMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/division2/escalation/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List escalation weeks (newest first) with optional date-range filter. */
        get: operations["EscalationController_listWeeks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/division2/escalation/weeks/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the still-active escalation week (most recent Tuesday ≤ today UTC), with embedded dailies. */
        get: operations["EscalationController_getCurrentWeek"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/division2/escalation/weeks/{weekStart}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single escalation week by its Tuesday weekStart, with embedded dailies. */
        get: operations["EscalationController_getWeekByWeekStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/division2/escalation/dailies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List daily-loot rows (newest first) with optional weekStart and date-range filters. */
        get: operations["EscalationController_listDailies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/division2/escalation/dailies/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single daily-loot row by its calendar day, with embedded week summary. */
        get: operations["EscalationController_getDailyByDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/division2/escalation/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger an upstream sync and per-guild dispatch for today’s daily loot. Mirrors the hourly cron, with optional `force` and per-guild scoping. */
        post: operations["EscalationController_triggerSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leveling/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated user’s current level, XP, and progress to the next level. */
        get: operations["LevelingController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leveling/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the guild leaderboard plus the caller’s own ranked entry. */
        get: operations["LevelingController_leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["StatusController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AfkRecordResponseDto: {
            id: string;
            discordId: string;
            guildId: string;
            reason?: Record<string, never> | null;
            /** @description False once the AFK session has ended. */
            isValid: boolean;
            /** @description When the AFK session started (ISO 8601). */
            createdAt: string;
            /** @description Last time the record was modified (ISO 8601). */
            updatedAt: string;
            /** @description When the AFK session ended (ISO 8601). Null while the session is still active. */
            endedAt?: Record<string, never> | null;
            /** @description Duration of the AFK session in milliseconds. For active sessions, measured against the time the response was generated. */
            durationMs: number;
        };
        AfkHistoryResponseDto: {
            items: components["schemas"]["AfkRecordResponseDto"][];
            /** @description Total number of matching records. */
            total: number;
            /** @description Limit echoed back from the request. */
            limit: number;
            /** @description Offset echoed back from the request. */
            offset: number;
        };
        SetAfkBodyDto: {
            /** @description Optional reason shown alongside the AFK status. Max 200 characters. */
            reason?: string;
        };
        AfkRecordWithProfileResponseDto: {
            id: string;
            discordId: string;
            guildId: string;
            reason?: Record<string, never> | null;
            /** @description False once the AFK session has ended. */
            isValid: boolean;
            /** @description When the AFK session started (ISO 8601). */
            createdAt: string;
            /** @description Last time the record was modified (ISO 8601). */
            updatedAt: string;
            /** @description When the AFK session ended (ISO 8601). Null while the session is still active. */
            endedAt?: Record<string, never> | null;
            /** @description Duration of the AFK session in milliseconds. For active sessions, measured against the time the response was generated. */
            durationMs: number;
            username?: Record<string, never> | null;
            globalName?: Record<string, never> | null;
            nickname?: Record<string, never> | null;
            /** @description Best available display name (nickname → globalName → username). */
            displayName: string;
            /** @description Discord avatar hash; clients build the CDN URL. */
            avatar?: Record<string, never> | null;
        };
        AfkListResponseDto: {
            items: components["schemas"]["AfkRecordWithProfileResponseDto"][];
            /** @description Total number of matching records in the guild. */
            total: number;
            /** @description Limit echoed back from the request. */
            limit: number;
            /** @description Offset echoed back from the request. */
            offset: number;
        };
        DiscordLoginRequestDto: {
            /** @description Discord OAuth access token obtained by the frontend (scope: identify). */
            discordAccessToken: string;
        };
        IconUrlsDto: {
            /** @description CDN URL at 64x64. */
            64: string;
            /** @description CDN URL at 128x128. */
            128: string;
            /** @description CDN URL at 256x256. */
            256: string;
            /** @description CDN URL at 512x512. */
            512: string;
        };
        DiscordRoleDto: {
            id: string;
            name: string;
            /** @description Hex color (#rrggbb), or null when the role has no color set. */
            color: string | null;
            /** @description Multi-size icon URLs, or null when no custom icon is set. */
            iconUrls: components["schemas"]["IconUrlsDto"] | null;
            /** @description Unicode emoji used as a fallback icon when no custom icon is set. */
            unicodeEmoji: string | null;
            /** @description Higher position is rendered above lower in Discord. */
            position: number;
            /** @description Whether the role is displayed separately in the member list. */
            hoist: boolean;
            mentionable: boolean;
            /** @description True for integration-managed roles (e.g. booster role, bot roles). */
            managed: boolean;
        };
        AuthUserDto: {
            discordId: string;
            guildId: string;
            username?: string;
            globalName?: Record<string, never> | null;
            nickname?: Record<string, never> | null;
            /** @description Multi-size URLs for the user's global avatar, or null when no avatar is set. */
            avatarUrls: components["schemas"]["IconUrlsDto"] | null;
            roles: ("DISCORD_ROLE_DEVELOPER" | "DISCORD_ROLE_TICKET_RESOLVER" | "DISCORD_ROLE_AFK" | "DISCORD_ROLE_QUARANTINE" | "DISCORD_ROLE_PENDING_VERIFICATION" | "DISCORD_ROLE_NOTIFY_ABOUT_PENDING_VERIFICATION" | "DISCORD_ROLE_BOOSTER" | "DISCORD_ROLE_STAFF")[];
            /** @description All Discord roles the member holds, sorted by position desc; @everyone excluded. */
            discordRoles: components["schemas"]["DiscordRoleDto"][];
            /** @description ISO 8601 timestamp of when the user joined the guild. */
            joinedAt: string | null;
            /** @description ISO 8601 timestamp of when the user started server-boosting. */
            premiumSince: string | null;
            /** @description ISO 8601 timestamp of when the Discord account was created (derived from the snowflake). */
            accountCreatedAt: string;
            /** @description Multi-size URLs for the guild-specific avatar override, or null when the user uses their global avatar. */
            serverAvatarUrls: components["schemas"]["IconUrlsDto"] | null;
        };
        AuthTokensResponseDto: {
            accessToken: string;
            refreshToken: string;
            /** @description Access token TTL in seconds. */
            expiresIn: number;
            user: components["schemas"]["AuthUserDto"];
        };
        RefreshRequestDto: {
            /** @description Previously issued refresh token. */
            refreshToken: string;
        };
        MeResponseDto: {
            user: components["schemas"]["AuthUserDto"];
        };
        ValidateApiTokenDto: Record<string, never>;
        CommunityStatsDto: {
            /** @description Active members in the guild (excluding members who have left). */
            totalMembers: number;
            /** @description Active members who joined within the last 14 days. */
            joinedLast14d: number;
            /** @description All-time total of completed voice-channel time across the guild, in whole minutes (floored). */
            totalVoiceMinutes: number;
            /** @description All-time total of user messages logged in the guild, including ones that were later deleted. Bot messages are not logged and therefore not counted. */
            totalMessages: number;
            /** @description ISO 8601 timestamp marking when this snapshot was generated. */
            generatedAt: string;
        };
        CommunityMemberDto: {
            discordId: string;
            username?: Record<string, never> | null;
            globalName?: Record<string, never> | null;
            nickname?: Record<string, never> | null;
            /** @description Best available display name (nickname → globalName → username). */
            displayName: string;
            /** @description Multi-size URLs for the user's global avatar, or null when no avatar is set. */
            avatarUrls: components["schemas"]["IconUrlsDto"] | null;
            /** @description Multi-size URLs for the guild-specific avatar override, or null when the user uses their global avatar. */
            serverAvatarUrls: components["schemas"]["IconUrlsDto"] | null;
            /** @description ISO 8601 timestamp of when the user joined the guild. */
            joinedAt: string | null;
            /** @description ISO 8601 timestamp of when the user started server-boosting. */
            premiumSince: string | null;
            /** @description ISO 8601 timestamp of when the Discord account was created (derived from the snowflake). */
            accountCreatedAt: string;
            /** @description Discord role IDs the member currently holds. Join client-side against /community/roles. */
            roleIds: string[];
        };
        CommunityMembersPageDto: {
            items: components["schemas"]["CommunityMemberDto"][];
            /** @description Total number of active members matching the query. */
            total: number;
            /** @description Limit echoed back from the request. */
            limit: number;
            /** @description Offset echoed back from the request. */
            offset: number;
        };
        CommunityMemberSlimDto: {
            discordId: string;
            /** @description Best available display name (nickname → globalName → username). */
            displayName: string;
            /** @description Pre-built CDN URL for the global avatar, or null when no avatar is set. */
            avatar: string | null;
        };
        ContentDigestDto: {
            /** @description Internal entity UUID. */
            id: string;
            /** @description Topic / game this digest covers. */
            topic: string;
            /** @description Digest frequency (daily or weekly). */
            frequency: string;
            /** @description Period start date (ISO 8601). */
            periodStart: string;
            /** @description Period end date (ISO 8601). */
            periodEnd: string;
            /** @description AI-generated digest title. */
            title: string;
            /** @description AI-generated short summary. */
            perex: string;
            /** @description AI-generated key takeaway bullet points. */
            highlights?: string[];
            /** @description AI-generated full digest body in Markdown format. */
            content: string;
            /** @description AI-selected thumbnail URL from source articles. */
            thumbnailUrl?: Record<string, never>;
            /** @description Number of articles included in this digest. */
            articleCount: number;
            /** @description UUIDs of articles included in this digest. */
            articleIds: string[];
            /** @description When the digest was created (ISO 8601). */
            createdAt: string;
            /** @description When the digest was last updated (ISO 8601). */
            updatedAt: string;
        };
        ContentDigestListDto: {
            items: components["schemas"]["ContentDigestDto"][];
            /** @description Total number of digests matching the query. */
            total: number;
            /** @description Limit echoed back from the request. */
            limit: number;
            /** @description Offset echoed back from the request. */
            offset: number;
        };
        GenerateDigestBodyDto: {
            /** @description Topic to generate digest for. Omit to generate for all topics. */
            topic?: string;
            /**
             * @description Frequency to generate. Omit to generate both daily and weekly.
             * @enum {string}
             */
            frequency?: "daily" | "weekly";
            /** @description Target date (ISO 8601, e.g. 2026-04-05). For daily: the day to cover. For weekly: any day in the target week. Defaults to yesterday (daily) / previous week (weekly). */
            date?: string;
        };
        ContentDigestGenerateResultDto: {
            /** @description Number of digests generated. */
            generated: number;
            /** @description Number of topic/frequency combinations skipped (no articles). */
            skipped: number;
            digests: components["schemas"]["ContentDigestDto"][];
        };
        ContentArticleDto: {
            /** @description Internal entity UUID. */
            id: string;
            /** @description Source system (e.g. UBISOFT, REDDIT). */
            source: string;
            /** @description External identifier from the source system. */
            sourceId: string;
            /** @description Topic / game this article relates to. */
            topic: string;
            /**
             * @description Publication date (ISO 8601).
             * @example 2026-04-01T12:34:56.000Z
             */
            publishedAt: string;
            /** @description Article headline. */
            title: string;
            /** @description Short summary / lead paragraph. */
            perex?: Record<string, never>;
            /** @description Full article body in Markdown format. */
            content?: Record<string, never>;
            /** @description Thumbnail image URL. */
            thumbnailUrl?: Record<string, never>;
            /** @description URL to the article on the source website. */
            url?: Record<string, never>;
            /** @description Article author(s). */
            authors?: Record<string, never>;
            /** @description Content tags. */
            tags?: string[];
            /** @description Source-specific metadata. */
            metadata?: Record<string, never>;
            /** @description When the article was last synced from the source (ISO 8601). */
            fetchedAt: string;
            /** @description AI-assigned relevance score (1-5). */
            relevance?: Record<string, never>;
            /** @description AI-generated summary of the content. */
            aiSummary?: Record<string, never>;
            /** @description AI-generated game-specific tags. */
            aiTags?: string[];
            /** @description AI-classified content type (e.g. news, guide, discussion). */
            contentType?: Record<string, never>;
        };
        ContentListDto: {
            items: components["schemas"]["ContentArticleDto"][];
            /** @description Total number of articles matching the query. */
            total: number;
            /** @description Limit echoed back from the request. */
            limit: number;
            /** @description Offset echoed back from the request. */
            offset: number;
        };
        ContentSyncResultDto: {
            /** @description The source that was synced. */
            source: string;
            /** @description Number of newly inserted articles. */
            inserted: number;
            /** @description Number of existing articles updated with fresh content. */
            updated: number;
            /** @description Number of pages fetched from the source API during the sync. */
            pagesScanned: number;
        };
        ChannelDto: {
            id: string;
            name: string;
            /** @description Channel type (e.g. text, voice, category, announcement) */
            type: string;
            parentId?: Record<string, never>;
            position: number;
            topic?: Record<string, never>;
        };
        ChannelMessageDto: {
            id: string;
            content: string;
            authorId: string;
            authorName: string;
            /** @description Author avatar URL */
            authorAvatar?: Record<string, never>;
            authorIsBot: boolean;
            createdAt: string;
            editedAt?: Record<string, never>;
        };
        EscalationMissionDto: {
            /**
             * @description Zero-based slot for this mission within the week. Pairs 1:1 with the targeted-loot item at the same `position` on each daily.
             * @example 0
             */
            position: number;
            /**
             * @description URL-friendly slug derived from the mission name.
             * @example the-art-museum
             */
            slug: string;
            /**
             * @description Human-readable mission name.
             * @example The Art Museum
             */
            name: string;
        };
        EscalationWeekListItemDto: {
            /**
             * @description The Tuesday this escalation week starts on (UTC).
             * @example 2026-05-05
             */
            weekStart: string;
            /**
             * @description When this week was last synced from upstream (ISO 8601).
             * @example 2026-05-05T11:23:11.000Z
             */
            fetchedAt: string;
            /** @description Five missions active during this week, sorted by `position` ASC. mission[position] is paired 1:1 with the targeted-loot item at the same `position` on every daily of this week. */
            missions: components["schemas"]["EscalationMissionDto"][];
            /**
             * @description Number of daily-loot rows ingested for this week so far.
             * @example 3
             */
            dailyCount: number;
        };
        EscalationWeekListDto: {
            items: components["schemas"]["EscalationWeekListItemDto"][];
            /** @description Total number of weeks matching the query. */
            total: number;
            /** @description Limit echoed back from the request. */
            limit: number;
            /** @description Offset echoed back from the request. */
            offset: number;
        };
        EscalationLootItemDto: {
            /**
             * @description Zero-based slot for this loot item within the day. Pairs 1:1 with the mission at the same `position` on the parent week — i.e. running mission[position] today drops loot[position].
             * @example 0
             */
            position: number;
            /**
             * @description URL-friendly slug derived from the loot-type name (weapon class, gear slot, or brand).
             * @example shotgun
             */
            slug: string;
            /**
             * @description Human-readable loot-type name.
             * @example Shotgun
             */
            name: string;
        };
        EscalationLootTypeRefDto: {
            /**
             * @description URL-friendly slug derived from the loot-type name (weapon class or gear slot).
             * @example holster
             */
            slug: string;
            /**
             * @description Human-readable loot-type name.
             * @example Holster
             */
            name: string;
        };
        EscalationPrototypeCacheDto: {
            /** @description The gear slot sold as a prototype gear cache by the escalation vendor on this day, or null when upstream did not publish the value. */
            gear: components["schemas"]["EscalationLootTypeRefDto"] | null;
            /** @description The weapon class sold as a prototype weapon cache by the escalation vendor on this day, or null when upstream did not publish the value. */
            weapon: components["schemas"]["EscalationLootTypeRefDto"] | null;
        };
        EscalationDailySummaryDto: {
            /**
             * @description The calendar day this targeted-loot rotation applies to (UTC).
             * @example 2026-05-07
             */
            day: string;
            /**
             * @description When this day was last synced from upstream (ISO 8601).
             * @example 2026-05-07T10:14:02.000Z
             */
            fetchedAt: string;
            /** @description Targeted-loot items for this day, sorted by `position` ASC. item[position] drops from the parent week's mission at the same `position`. */
            items: components["schemas"]["EscalationLootItemDto"][];
            /** @description Prototype caches sold by the escalation vendor on this day — one gear slot and one weapon class, independent of the mission/loot pairing on `items`. Either side is null when upstream did not publish that value. */
            prototypeCaches: components["schemas"]["EscalationPrototypeCacheDto"];
        };
        EscalationWeekDetailDto: {
            /**
             * @description The Tuesday this escalation week starts on (UTC).
             * @example 2026-05-05
             */
            weekStart: string;
            /**
             * @description When this week was last synced from upstream (ISO 8601).
             * @example 2026-05-05T11:23:11.000Z
             */
            fetchedAt: string;
            /** @description Five missions active during this week, sorted by `position` ASC. mission[position] is paired 1:1 with the targeted-loot item at the same `position` on every daily of this week. */
            missions: components["schemas"]["EscalationMissionDto"][];
            /** @description Daily-loot rows ingested for this week so far, ordered by day ascending. */
            dailies: components["schemas"]["EscalationDailySummaryDto"][];
        };
        EscalationDailyListItemDto: {
            /**
             * @description The calendar day this targeted-loot rotation applies to (UTC).
             * @example 2026-05-07
             */
            day: string;
            /**
             * @description The Tuesday this day belongs to (UTC).
             * @example 2026-05-05
             */
            weekStart: string;
            /**
             * @description When this day was last synced from upstream (ISO 8601).
             * @example 2026-05-07T10:14:02.000Z
             */
            fetchedAt: string;
            /**
             * @description Number of targeted-loot items in this day.
             * @example 4
             */
            itemCount: number;
            /** @description Prototype caches sold by the escalation vendor on this day — one gear slot and one weapon class. Either side is null when upstream did not publish that value. */
            prototypeCaches: components["schemas"]["EscalationPrototypeCacheDto"];
        };
        EscalationDailyListDto: {
            items: components["schemas"]["EscalationDailyListItemDto"][];
            /** @description Total number of dailies matching the query. */
            total: number;
            /** @description Limit echoed back from the request. */
            limit: number;
            /** @description Offset echoed back from the request. */
            offset: number;
        };
        EscalationWeekSummaryDto: {
            /**
             * @description The Tuesday this escalation week starts on (UTC).
             * @example 2026-05-05
             */
            weekStart: string;
            /**
             * @description When this week was last synced from upstream (ISO 8601).
             * @example 2026-05-05T11:23:11.000Z
             */
            fetchedAt: string;
            /** @description Five missions active during this week, sorted by `position` ASC. mission[position] is paired 1:1 with the targeted-loot item at the same `position` on every daily of this week. */
            missions: components["schemas"]["EscalationMissionDto"][];
        };
        EscalationDailyDetailDto: {
            /**
             * @description The calendar day this targeted-loot rotation applies to (UTC).
             * @example 2026-05-07
             */
            day: string;
            /**
             * @description When this day was last synced from upstream (ISO 8601).
             * @example 2026-05-07T10:14:02.000Z
             */
            fetchedAt: string;
            /** @description Targeted-loot items for this day, sorted by `position` ASC. item[position] drops from `week.missions[position]`. */
            items: components["schemas"]["EscalationLootItemDto"][];
            /** @description Prototype caches sold by the escalation vendor on this day — one gear slot and one weapon class, independent of the mission/loot pairing on `items`. Either side is null when upstream did not publish that value. */
            prototypeCaches: components["schemas"]["EscalationPrototypeCacheDto"];
            /** @description Summary of the week this day belongs to. */
            week: components["schemas"]["EscalationWeekSummaryDto"];
        };
        SyncEscalationBodyDto: {
            /**
             * @description When true, deletes today’s claim row(s) before re-dispatching so the post goes out again. Old Discord messages are not edited or deleted — expect duplicates in the channel.
             * @default false
             */
            force: boolean;
            /**
             * @description Optional Discord guild snowflake to scope the dispatch to a single guild. Omit to operate on every enabled guild (matches the cron).
             * @example 1234567890123456789
             */
            guildId?: string;
        };
        EscalationDispatchOutcomeDto: {
            /**
             * @description The Discord guild snowflake.
             * @example 1234567890123456789
             */
            guildId: string;
            /**
             * @description The configured target channel snowflake. Null when the guild was not enabled.
             * @example 9876543210987654321
             */
            channelId: Record<string, never> | null;
            /**
             * @description Outcome of the dispatch attempt. `queued` = claim acquired and post emitted (actual send is async); `skipped-already-posted` = a claim row already existed for today; `skipped-not-enabled` = a `guildId` was supplied but is not in the enabled-target list.
             * @enum {string}
             */
            status: "queued" | "skipped-already-posted" | "skipped-not-enabled";
            /** @description True when this guild’s claim row was force-cleared on this run before re-claiming. */
            forceCleared?: boolean;
        };
        EscalationSyncResultDto: {
            /** @description Number of upstream weeks scanned during this run. */
            weeksProcessed: number;
            /** @description Number of upstream daily-loot rows seen across all weeks. */
            daysIngested: number;
            /** @description Number of daily-loot rows newly inserted on this run. */
            newDaysIngested: number;
            /** @description Number of prototype-cache rows attached to *already-existing* daily-loot rows on this run. Counts the backfill of legacy days that were ingested before caches existed; excludes caches saved as part of brand-new daily rows. */
            prototypeCachesBackfilled: number;
            /**
             * @description The most recent upstream day seen, in YYYY-MM-DD form. Null when nothing was seen.
             * @example 2026-05-10
             */
            latestDay: Record<string, never> | null;
            /** @description Whether today’s daily-loot row is now in the database. When false, no dispatch was attempted because there is nothing to post. */
            todayDailyIngested: boolean;
            /** @description Number of (guild, today) claim rows that were deleted as part of `force=true`. Always 0 when `force` was false. */
            forceClearedRows: number;
            /** @description Per-guild dispatch outcomes. Empty when today’s daily was not yet ingested or no guilds had the feature enabled. */
            dispatched: components["schemas"]["EscalationDispatchOutcomeDto"][];
        };
        NextLevelDto: {
            /** @description Numeric index of the next configured level. */
            level: number;
            /** @description Total XP the user must accumulate to reach this level. */
            xpRequired: number;
            /** @description Optional label configured for this level. */
            label?: Record<string, never> | null;
        };
        OwnLevelResponseDto: {
            discordId: string;
            guildId: string;
            /** @description The level the user has currently reached. */
            level: number;
            /** @description Label configured for the current level, if any. */
            levelLabel?: Record<string, never> | null;
            /** @description Total XP earned by the user in this guild. */
            xp: number;
            /** @description Next configured level, or null when the user is already at the highest configured level. */
            nextLevel?: components["schemas"]["NextLevelDto"] | null;
            /** @description XP remaining until the next level, or null when there is no next level. */
            xpToNextLevel?: Record<string, never> | null;
            /** @description Progress within the current level band, in the inclusive range [0, 1]. */
            progress: number;
        };
        LeaderboardEntryDto: {
            /** @description 1-indexed rank within the guild leaderboard sort. */
            rank: number;
            discordId: string;
            username?: Record<string, never> | null;
            globalName?: Record<string, never> | null;
            nickname?: Record<string, never> | null;
            /** @description Best available display name (nickname → globalName → username). */
            displayName: string;
            /** @description Discord avatar hash; clients build the CDN URL. */
            avatar?: Record<string, never> | null;
            level: number;
            xp: number;
        };
        LeaderboardResponseDto: {
            items: components["schemas"]["LeaderboardEntryDto"][];
            /** @description Total number of leveled users in the guild. */
            total: number;
            /** @description Limit echoed back from the request. */
            limit: number;
            /** @description Offset echoed back from the request. */
            offset: number;
            /** @description Caller’s own leaderboard entry; null when the caller has not earned XP in this guild. */
            me?: components["schemas"]["LeaderboardEntryDto"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AfkController_getOwnStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active AFK record, or null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AfkRecordResponseDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AfkController_setOwnAfk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAfkBodyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AfkRecordResponseDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not a member of the guild bound to this token. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is already AFK; clear first before setting again. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Guild has no AFK role configured. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AfkController_clearOwnAfk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not a member of the guild bound to this token. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Guild has no AFK role configured. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AfkController_getOwnHistory: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Optional filter on AFK record validity. Omit to return both active and ended records; pass `true` for active only, `false` for ended only. */
                isValid?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AfkHistoryResponseDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AfkController_listGuildAfk: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Optional filter on AFK record validity. Omit to return both active and ended records; pass `true` for active only, `false` for ended only. */
                isValid?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AfkListResponseDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller lacks the STAFF role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AfkController_getUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active AFK record, or null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AfkRecordWithProfileResponseDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller lacks the STAFF role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AfkController_setUserAfk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAfkBodyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AfkRecordWithProfileResponseDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller lacks the STAFF role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Target user is not a member of the guild bound to this token. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Target user is already AFK; clear first before setting again. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Guild has no AFK role configured. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AfkController_clearUserAfk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller lacks the STAFF role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Target user is not a member of the guild bound to this token. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Guild has no AFK role configured. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AfkController_getUserHistory: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Optional filter on AFK record validity. Omit to return both active and ended records; pass `true` for active only, `false` for ended only. */
                isValid?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AfkListResponseDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller lacks the STAFF role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscordLoginRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponseDto"];
                };
            };
            /** @description Invalid X-API-Key or Discord access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is not a member of the application guild. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponseDto"];
                };
            };
            /** @description Invalid, expired, revoked, or reused refresh token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    AuthTokenController_validate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token is valid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateApiTokenDto"];
                };
            };
            /** @description Missing, invalid, revoked, or expired token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommunityController_getRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscordRoleDto"][];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommunityController_getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityStatsDto"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommunityController_getRecent: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityMembersPageDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommunityController_autocomplete: {
        parameters: {
            query?: {
                /** @description Case-insensitive name fragment matched against nickname, globalName, and username. */
                q?: string;
                /** @description Comma-separated list of Discord IDs to hydrate. Max 100. */
                ids?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityMemberSlimDto"][];
                };
            };
            /** @description q must be at least 2 characters when provided. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommunityController_lookup: {
        parameters: {
            query: {
                /** @description Comma-separated list of Discord IDs to hydrate. Required, max 100. */
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityMemberDto"][];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommunityController_getDirectory: {
        parameters: {
            query?: {
                /** @description Case-insensitive name fragment matched against nickname, globalName, and username. */
                q?: string;
                sort?: "joinedAt" | "name";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityMembersPageDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommunityController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityMemberDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Member not found in this guild or has left. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentDigestController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filter by topic (e.g. division-2, xdefiant). */
                topic?: string;
                /** @description Filter by frequency (daily or weekly). */
                frequency?: "daily" | "weekly";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of digests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDigestListDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentDigestController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Digest details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDigestDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Digest not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentDigestController_generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateDigestBodyDto"];
            };
        };
        responses: {
            /** @description Generation completed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDigestGenerateResultDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filter by source (e.g. UBISOFT, REDDIT). */
                source?: "UBISOFT" | "REDDIT" | "YOUTUBE";
                /** @description Filter by topic (e.g. division-2, xdefiant). */
                topic?: string;
                /** @description Filter by AI-classified content type (e.g. news, guide, discussion). */
                contentType?: string;
                /** @description Minimum AI relevance score (1-5). */
                minRelevance?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of articles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentListDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentArticleDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Article not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentController_triggerSync: {
        parameters: {
            query: {
                source: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync completed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSyncResultDto"][];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DiscordChannelController_getChannels: {
        parameters: {
            query?: {
                /** @description Filter channels by role ViewChannel permission */
                roleId?: string;
                /** @description Filter channels by guild member ViewChannel permission */
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of channels. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelDto"][];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DiscordChannelController_getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DiscordChannelController_getMessages: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Message ID cursor for pagination (fetch messages before this ID) */
                before?: string;
            };
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of messages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelMessageDto"][];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EscalationController_listWeeks: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Lower bound on weekStart (inclusive), as YYYY-MM-DD. */
                from?: string;
                /** @description Upper bound on weekStart (inclusive), as YYYY-MM-DD. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of weeks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationWeekListDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EscalationController_getCurrentWeek: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current week. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationWeekDetailDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No escalation week has been ingested yet. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EscalationController_getWeekByWeekStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Tuesday weekStart in YYYY-MM-DD format. */
                weekStart: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matching week. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationWeekDetailDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No week exists for the supplied weekStart. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EscalationController_listDailies: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filter to dailies whose parent week starts on this date (YYYY-MM-DD). */
                weekStart?: string;
                /** @description Lower bound on day (inclusive), as YYYY-MM-DD. */
                from?: string;
                /** @description Upper bound on day (inclusive), as YYYY-MM-DD. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of dailies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationDailyListDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EscalationController_getDailyByDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The calendar day in YYYY-MM-DD format. */
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matching daily. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationDailyDetailDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No daily-loot row exists for the supplied day. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EscalationController_triggerSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncEscalationBodyDto"];
            };
        };
        responses: {
            /** @description Sync completed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationSyncResultDto"];
                };
            };
            /** @description Missing or invalid API token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LevelingController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnLevelResponseDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LevelingController_leaderboard: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponseDto"];
                };
            };
            /** @description Missing or invalid API key / bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StatusController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
