import 'server-only'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Server-only loader for the Division 2 icon asset map shipped under
 * `public/division2/data/asset_map.json`. The file is generated by an
 * out-of-band sync script; we just read it once at module load.
 *
 * Lookups are keyed by a normalized form (lowercase, alphanumeric only) so
 * any of "Hunter's Fury", "hunters-fury", "huntersfury" resolves to the
 * same icon.
 */

export type LootIconCategory = 'weapon_types' | 'gear_slots' | 'brands'

export type AssetMapCategory =
  | 'brands'
  | 'gear_slots'
  | 'weapon_types'
  | 'talents'
  | 'weapon_talents'

/**
 * Canonical shape of `public/division2/data/asset_map.json`.
 *
 * Single source of truth for both the server-side icon loader (this file)
 * and the BFF route at `app/api/division2/assets/route.ts`. Categories are
 * optional so a missing-file fallback (`{}` cast to this shape) doesn't lie
 * to TypeScript; consumers should default each category with `?? {}`.
 */
export interface AssetMapFile {
  version?: number
  built_at?: string
  source_built_at?: string | null
  sanitize?: unknown
  brands?: Record<string, string>
  gear_slots?: Record<string, string>
  weapon_types?: Record<string, string>
  talents?: Record<string, string>
  weapon_talents?: Record<string, string>
  missing?: Partial<Record<AssetMapCategory, string[]>>
}

const MAP_PATH = join(process.cwd(), 'public', 'division2', 'data', 'asset_map.json')

let cachedMap: AssetMapFile | null = null
let cachedLookup: Map<string, { url: string; category: LootIconCategory }> | null = null

function loadMap(): AssetMapFile {
  if (cachedMap) return cachedMap
  try {
    const raw = readFileSync(MAP_PATH, 'utf8')
    cachedMap = JSON.parse(raw) as AssetMapFile
  } catch {
    cachedMap = {}
  }
  return cachedMap
}

/** Normalize a name or slug for asset-map lookup — strips everything but a-z 0-9. */
function normalize(input: string): string {
  return input.toLowerCase().replace(/[^a-z0-9]/g, '')
}

function buildLookup(): Map<string, { url: string; category: LootIconCategory }> {
  if (cachedLookup) return cachedLookup
  const map = loadMap()
  const lookup = new Map<string, { url: string; category: LootIconCategory }>()
  // Order matters only on duplicate normalized keys — categories are disjoint
  // in practice, but if a collision ever exists, weapon_types wins (they
  // appear in prototype caches AND targeted loot, so we want them stable).
  const order: LootIconCategory[] = ['weapon_types', 'gear_slots', 'brands']
  for (const category of order) {
    const entries = map[category] ?? {}
    for (const [key, relPath] of Object.entries(entries)) {
      const k = normalize(key)
      if (!lookup.has(k)) {
        lookup.set(k, { url: `/division2/${relPath}`, category })
      }
    }
  }
  cachedLookup = lookup
  return lookup
}

/**
 * Resolve a loot name or slug to its public icon URL.
 * Returns null when the asset map doesn't have a matching key — caller
 * should fall back to text only.
 */
export function resolveLootIcon(
  slugOrName: string | null | undefined,
): { url: string; category: LootIconCategory } | null {
  if (!slugOrName) return null
  const k = normalize(slugOrName)
  if (!k) return null
  return buildLookup().get(k) ?? null
}
