/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    series: Series;
    games: Game;
    topics: Topic;
    'content-types': ContentType;
    media: Media;
    users: User;
    members: Member;
    'read-progress': ReadProgress;
    bookmarks: Bookmark;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    'content-types': ContentTypesSelect<false> | ContentTypesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'read-progress': ReadProgressSelect<false> | ReadProgressSelect<true>;
    bookmarks: BookmarksSelect<false> | BookmarksSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  slug: string;
  publishedAt?: string | null;
  readingTime?: number | null;
  title: string;
  /**
   * Short excerpt/description shown in article listings
   */
  perex: string;
  heroImage: string | Media;
  /**
   * Curated articles to show in "You might also like" section. Leave empty for automatic selection.
   */
  relatedArticles?: (string | Article)[] | null;
  categorization: {
    /**
     * Primary content type (Guide, Build, News, etc.)
     */
    topic: string | Topic;
    /**
     * Optional: Link to specific games this article is about
     */
    games?: (string | Game)[] | null;
    /**
     * Content format: Article, Video, Podcast, etc.
     */
    contentType: string | ContentType;
  };
  articleContent?: {
    /**
     * Choose where the article content comes from
     */
    contentSource?: ('payload' | 'wiki') | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Select a published document from the Outline wiki
     */
    outlineDocumentId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: string;
  name: string;
  /**
   * Auto-generated from name. Used in URLs.
   */
  slug: string;
  color: 'orange' | 'blue' | 'yellow' | 'teal' | 'green' | 'purple' | 'red' | 'pink';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: string;
  name: string;
  subtitle?: string | null;
  description?: string | null;
  color: 'orange' | 'blue' | 'yellow' | 'teal' | 'green' | 'purple' | 'red' | 'pink';
  /**
   * Shows "Main Game" badge and larger display
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-types".
 */
export interface ContentType {
  id: string;
  name: string;
  /**
   * Auto-generated from name. Used in URLs.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: string;
  name: string;
  /**
   * Auto-generated from name. Used in URLs.
   */
  slug: string;
  /**
   * Brief description of this series
   */
  description?: string | null;
  /**
   * Optional hero image for the series. Falls back to first article hero if not set.
   */
  heroImage?: (string | null) | Media;
  /**
   * Articles in this series. Drag to reorder - the order here defines the series order.
   */
  articles?: (string | Article)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Discord members who have authenticated via OAuth
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  /**
   * Discord user ID
   */
  discordId: string;
  /**
   * Discord username
   */
  username: string;
  /**
   * Discord display name
   */
  globalName?: string | null;
  /**
   * Discord avatar hash
   */
  avatar?: string | null;
  /**
   * Discord email (if provided)
   */
  email?: string | null;
  /**
   * Guild membership information
   */
  guildMember?: {
    /**
     * Server nickname
     */
    nickname?: string | null;
    /**
     * Array of Discord role IDs
     */
    roles?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * When they joined the Discord server
     */
    joinedDiscordAt?: string | null;
  };
  /**
   * First login to this site
   */
  joinedAt: string;
  /**
   * Most recent login
   */
  lastLogin: string;
  /**
   * Set to Banned to revoke access
   */
  status: 'active' | 'banned' | 'left_server';
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks article reading progress for members
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "read-progress".
 */
export interface ReadProgress {
  id: string;
  member: string | Member;
  article: string | Article;
  /**
   * Scroll percentage (0-100)
   */
  progress: number;
  /**
   * When the member first visited this article
   */
  firstVisitedAt: string;
  /**
   * When the member last visited this article
   */
  lastVisitedAt: string;
  /**
   * Total time spent reading (seconds)
   */
  timeSpent: number;
  /**
   * True when progress reaches 85% or higher
   */
  completed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Member bookmarked articles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks".
 */
export interface Bookmark {
  id: string;
  member: string | Member;
  article: string | Article;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'series';
        value: string | Series;
      } | null)
    | ({
        relationTo: 'games';
        value: string | Game;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null)
    | ({
        relationTo: 'content-types';
        value: string | ContentType;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'read-progress';
        value: string | ReadProgress;
      } | null)
    | ({
        relationTo: 'bookmarks';
        value: string | Bookmark;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  publishedAt?: T;
  readingTime?: T;
  title?: T;
  perex?: T;
  heroImage?: T;
  relatedArticles?: T;
  categorization?:
    | T
    | {
        topic?: T;
        games?: T;
        contentType?: T;
      };
  articleContent?:
    | T
    | {
        contentSource?: T;
        content?: T;
        outlineDocumentId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  heroImage?: T;
  articles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  name?: T;
  subtitle?: T;
  description?: T;
  color?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-types_select".
 */
export interface ContentTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  discordId?: T;
  username?: T;
  globalName?: T;
  avatar?: T;
  email?: T;
  guildMember?:
    | T
    | {
        nickname?: T;
        roles?: T;
        joinedDiscordAt?: T;
      };
  joinedAt?: T;
  lastLogin?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "read-progress_select".
 */
export interface ReadProgressSelect<T extends boolean = true> {
  member?: T;
  article?: T;
  progress?: T;
  firstVisitedAt?: T;
  lastVisitedAt?: T;
  timeSpent?: T;
  completed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks_select".
 */
export interface BookmarksSelect<T extends boolean = true> {
  member?: T;
  article?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  /**
   * Tagline text displayed under the headline
   */
  claim?: string | null;
  /**
   * Drag to reorder games on the homepage
   */
  games?: (string | Game)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  claim?: T;
  games?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlockType".
 */
export interface CalloutBlockType {
  type: 'info' | 'warning' | 'tip' | 'success' | 'danger' | 'error' | 'note';
  title?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlockType".
 */
export interface CodeBlockType {
  language:
    | 'typescript'
    | 'javascript'
    | 'tsx'
    | 'jsx'
    | 'python'
    | 'ruby'
    | 'go'
    | 'rust'
    | 'cpp'
    | 'c'
    | 'csharp'
    | 'java'
    | 'php'
    | 'swift'
    | 'kotlin'
    | 'sql'
    | 'json'
    | 'yaml'
    | 'xml'
    | 'html'
    | 'css'
    | 'scss'
    | 'markdown'
    | 'bash'
    | 'powershell'
    | 'dockerfile'
    | 'graphql'
    | 'prisma'
    | 'text';
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'codeBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MermaidBlockType".
 */
export interface MermaidBlockType {
  /**
   * Enter Mermaid diagram syntax (flowchart, sequence, etc.)
   */
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mermaid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialEmbedBlockType".
 */
export interface SocialEmbedBlockType {
  /**
   * Supports tweets, posts, reels, and videos from public accounts
   */
  url: string;
  /**
   * Additional context shown beneath the embedded post
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'socialEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlockType".
 */
export interface VideoEmbedBlockType {
  /**
   * Supports videos, playlists, channels, clips, and live streams
   */
  url: string;
  /**
   * Used as the iframe title attribute for screen readers
   */
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}